services:
  - type: web
    name: neuro-glow-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    plan: free
